### ISSUE TITLE
Can't import or build properly

### ISSUE THREAD

**Issue by Teityan** [jctim/otp-ciq#3]
I use Venu and imported it into Eclipce to try to see if I could use it, and then tried to experiment with the emulator.
However, it was not recognized as a ConnectIQ project and could not be built and run in the emulator.
However, the sample program worked.
Do you have a solution?
![image](https://user-images.githubusercontent.com/33191007/88067977-91d8ba00-cbaa-11ea-9bc1-30ce1bed08df.png)
![image](https://user-images.githubusercontent.com/33191007/88068028-9ef5a900-cbaa-11ea-9d01-6279d4da1462.png)
![image](https://user-images.githubusercontent.com/33191007/88068093-b92f8700-cbaa-11ea-8f1f-6ea988a492fa.png)

**Comment by jctim** [comment]
Yeah, they recommend to use VS code https://developer.garmin.com/connect-iq/sdk/
